typography_spectrum: 0.5606185481883585
color:
  saturation: 0.4931590708438307
  brandStrength: 0.8921513366512954
  lightness: 0.6345736412331462
  brandColors:
    - '#B5DBE5'
    - '#9A9C97'
    - '#254B8A'
    - '#767F7C'
    - '#46BBD1'
  rhythmicContrast: 0.6475135709624738
layout_spectrum: 0.4781243531033397
author:
  name: Denise Howell
  email: denise@howell.net
  url: ''
logo: null
name: lawyering down so you don't need to lawyer up
navigation:
  - name: contact
    id: 5c36916c-5cad-4679-b053-67189528b3f7
    type: content
  - name: elsewhere
    id: b4224666-7d5e-437d-824e-e38d063427a4
    type: content
  - name: other places
    id: 5e4e57ee-1550-47e6-a835-b7b7728ae30f
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5d98b6f5-dfb0-4ca2-9720-c4bde9e31da5.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: DENISE HOWELL
description: 'internet and technology lawyer. host, This WEEK in LAW.'
