typography_spectrum: 0.2712665640283376
color:
  saturation: 0.4402629
  brandStrength: 0.8106332
  lightness: 1
  brandColors:
    - '#FCFCFA'
    - '#4F4C67'
    - '#71293D'
    - '#A29A8F'
    - '#F5DA81'
  rhythmicContrast: 0.6123058
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/b97dd86d-e800-49ba-8a74-617a8f12be84.jpg
layout_spectrum: 0.06584785087034106
analytics:
  google: '83224671'
author:
  name: Denise Howell
  email: denise@howell.net
  url: ''
logo: null
name: >-
  8 out of 10 owners who expressed a preference said their cats preferred this
  lawyer.
navigation:
  - name: elsewhere
    id: b4224666-7d5e-437d-824e-e38d063427a4
    type: content
  - name: about
    id: f82a065a-2c61-4fc9-9615-0f2792325f5c
    type: content
  - name: contact
    id: 5c36916c-5cad-4679-b053-67189528b3f7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5d98b6f5-dfb0-4ca2-9720-c4bde9e31da5.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: DENISE HOWELL
description: "internet and technology lawyer. \_host, This WEEK in LAW."
