layout_spectrum: 0.9268017890863121
typography_spectrum: 0.07484253076836467
color:
  brandStrength: 0.4236874799244106
  lightness: 0.8905266313813627
  saturation: 0.1594988175202161
  rhythmicContrast: 0.7570899603888392
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
author:
  name: Denise Howell
  email: denise@howell.net
  url: ''
logo: null
name: 'don''t lawyer up, lawyer down'
navigation:
  - name: elsewhere
    id: 5e4e57ee-1550-47e6-a835-b7b7728ae30f
    type: content
title: DENISE HOWELL
description: 'internet and technology law.  host, This WEEK in LAW.'
