typography_spectrum: 0.1056235225405544
color:
  brandStrength: 0.3553201511967927
  lightness: 0.3794684340246022
  saturation: 0.6816225913353264
  rhythmicContrast: 0.5346299132797867
  brandColors:
    - '#849D41'
    - '#E3CDE4'
    - '#994717'
    - '#252122'
    - '#BD1A8D'
layout_spectrum: 0.009437795961275697
author:
  name: Denise Howell
  email: denise@howell.net
  url: ''
logo: null
name: denise howell
navigation:
  - name: elsewhere
    id: 5e4e57ee-1550-47e6-a835-b7b7728ae30f
    type: content
title: DENISE HOWELL
description: 'internet and technology law.  host, This WEEK in LAW.'
