typography_spectrum: 0.5606185481883585
color:
  brandStrength: 0.8921513366512954
  lightness: 0.6345736412331462
  saturation: 0.4931590708438307
  rhythmicContrast: 0.6475135709624738
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
layout_spectrum: 0.47812435310333967
author:
  name: Denise Howell
  email: denise@howell.net
  url: ''
logo: null
name: lawyering down so you don't need to lawyer up
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5d98b6f5-dfb0-4ca2-9720-c4bde9e31da5.ico
title: DENISE HOWELL
description: 'internet and technology lawyer. host, This WEEK in LAW.'
