title: DENISE HOWELL
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: 'internet and technology lawyer. host, This WEEK in LAW.'
color:
  saturation: 0.4931590708438307
  brandStrength: 0.8921513366512954
  rhythmicContrast: 0.6475135709624738
  brandColors:
    - '#B5DBE5'
    - '#9A9C97'
    - '#254B8A'
    - '#767F7C'
    - '#46BBD1'
  lightness: 0.6345736412331462
navigation:
  - name: contact
    id: 5c36916c-5cad-4679-b053-67189528b3f7
    type: content
  - name: elsewhere
    id: b4224666-7d5e-437d-824e-e38d063427a4
    type: content
  - name: CC
    id: c0e3482c-9953-48b4-8311-6ef28d1df0cd
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5d98b6f5-dfb0-4ca2-9720-c4bde9e31da5.ico
author:
  name: Denise Howell
  email: denise@howell.net
  url: ''
name: >-
  8 out of 10 owners who expressed a preference said their cats preferred this
  lawyer.
logo: null
typography_spectrum: 0.416368
layout_spectrum: 0.4781243531033397
