layout_spectrum: 0.47812435310333967
typography_spectrum: 0.5606185481883585
color:
  brandStrength: 0.8921513366512954
  lightness: 0.6345736412331462
  saturation: 0.4931590708438307
  rhythmicContrast: 0.6475135709624738
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
author:
  name: Denise Howell
  email: denise@howell.net
  url: ''
logo: null
name: 'don''t lawyer up, lawyer down'
navigation:
  - name: elsewhere
    id: 5e4e57ee-1550-47e6-a835-b7b7728ae30f
    type: content
title: DENISE HOWELL
description: 'internet and technology law.  host, This WEEK in LAW.'
